import {
  University,
  Faculty,
  Department,
  Course,
  Topic,
  WAECSubject,
  Question,
  User,
  ExamResult,
  UploadRecord,
  Achievement,
  CustomInstitutionAggregate,
} from '../src/types';

// In-memory relational database state with pre-seeded real academic data

export const UNIVERSITIES: University[] = [
  { id: 'uni_unilag', name: 'University of Lagos', short_name: 'UNILAG', state: 'Lagos', country: 'Nigeria', status: 'active', student_count: 3420 },
  { id: 'uni_ui', name: 'University of Ibadan', short_name: 'UI', state: 'Oyo', country: 'Nigeria', status: 'active', student_count: 2890 },
  { id: 'uni_oau', name: 'Obafemi Awolowo University', short_name: 'OAU', state: 'Osun', country: 'Nigeria', status: 'active', student_count: 3100 },
  { id: 'uni_uniben', name: 'University of Benin', short_name: 'UNIBEN', state: 'Edo', country: 'Nigeria', status: 'active', student_count: 2450 },
  { id: 'uni_lasu', name: 'Lagos State University', short_name: 'LASU', state: 'Lagos', country: 'Nigeria', status: 'active', student_count: 2150 },
  { id: 'uni_futa', name: 'Federal University of Technology, Akure', short_name: 'FUTA', state: 'Ondo', country: 'Nigeria', status: 'active', student_count: 1980 },
  { id: 'uni_abu', name: 'Ahmadu Bello University', short_name: 'ABU', state: 'Kaduna', country: 'Nigeria', status: 'active', student_count: 2700 },
  { id: 'uni_unn', name: 'University of Nigeria, Nsukka', short_name: 'UNN', state: 'Enugu', country: 'Nigeria', status: 'active', student_count: 2600 },
  { id: 'uni_covenant', name: 'Covenant University', short_name: 'CU', state: 'Ogun', country: 'Nigeria', status: 'active', student_count: 1450 },
  { id: 'uni_unilorin', name: 'University of Ilorin', short_name: 'UNILORIN', state: 'Kwara', country: 'Nigeria', status: 'active', student_count: 3150 },
];

export const FACULTIES: Faculty[] = [
  { id: 'fac_sci', university_id: 'uni_unilag', name: 'Faculty of Science', status: 'active' },
  { id: 'fac_eng', university_id: 'uni_unilag', name: 'Faculty of Engineering', status: 'active' },
  { id: 'fac_soc', university_id: 'uni_unilag', name: 'Faculty of Social Sciences', status: 'active' },
  { id: 'fac_art', university_id: 'uni_unilag', name: 'Faculty of Arts', status: 'active' },
  { id: 'fac_mgt', university_id: 'uni_unilag', name: 'Faculty of Management Sciences', status: 'active' },
  { id: 'fac_law', university_id: 'uni_unilag', name: 'Faculty of Law', status: 'active' },
];

export const DEPARTMENTS: Department[] = [
  { id: 'dept_csc', faculty_id: 'fac_sci', university_id: 'uni_unilag', name: 'Computer Science', status: 'active' },
  { id: 'dept_mth', faculty_id: 'fac_sci', university_id: 'uni_unilag', name: 'Mathematics', status: 'active' },
  { id: 'dept_bch', faculty_id: 'fac_sci', university_id: 'uni_unilag', name: 'Biochemistry', status: 'active' },
  { id: 'dept_eee', faculty_id: 'fac_eng', university_id: 'uni_unilag', name: 'Electrical & Electronics Engineering', status: 'active' },
  { id: 'dept_mech', faculty_id: 'fac_eng', university_id: 'uni_unilag', name: 'Mechanical Engineering', status: 'active' },
  { id: 'dept_eco', faculty_id: 'fac_soc', university_id: 'uni_unilag', name: 'Economics', status: 'active' },
  { id: 'dept_acc', faculty_id: 'fac_mgt', university_id: 'uni_unilag', name: 'Accounting & Finance', status: 'active' },
];

export const COURSES: Course[] = [
  {
    id: 'course_csc201',
    code: 'CSC 201',
    title: 'Data Structures and Algorithms',
    department_id: 'dept_csc',
    faculty_id: 'fac_sci',
    university_id: 'uni_unilag',
    level: '200',
    semester: '1st',
    description: 'Fundamental data structures: arrays, linked lists, stacks, queues, trees, graphs, sorting and asymptotic analysis.',
    status: 'active',
    mastery_percentage: 78,
    question_count: 85,
  },
  {
    id: 'course_csc203',
    code: 'CSC 203',
    title: 'Computer Architecture & Organization',
    department_id: 'dept_csc',
    faculty_id: 'fac_sci',
    university_id: 'uni_unilag',
    level: '200',
    semester: '1st',
    description: 'Logic circuits, CPU architecture, memory hierarchy, cache management, instruction pipeline, bus structures.',
    status: 'active',
    mastery_percentage: 64,
    question_count: 60,
  },
  {
    id: 'course_mth201',
    code: 'MTH 201',
    title: 'Mathematical Methods I (Linear Algebra)',
    department_id: 'dept_mth',
    faculty_id: 'fac_sci',
    university_id: 'uni_unilag',
    level: '200',
    semester: '1st',
    description: 'Vector spaces, matrices, determinants, eigenvalues, eigenvectors, systems of linear equations, linear transformations.',
    status: 'active',
    mastery_percentage: 70,
    question_count: 90,
  },
  {
    id: 'course_gst101',
    code: 'GST 101',
    title: 'Use of English and Study Skills',
    department_id: 'dept_csc',
    faculty_id: 'fac_art',
    university_id: 'uni_unilag',
    level: '100',
    semester: '1st',
    description: 'Grammar mechanics, subject-verb concord, comprehension techniques, paragraph structure, essay synthesis.',
    status: 'active',
    mastery_percentage: 88,
    question_count: 110,
  },
  {
    id: 'course_eee201',
    code: 'EEE 201',
    title: 'Circuit Theory I',
    department_id: 'dept_eee',
    faculty_id: 'fac_eng',
    university_id: 'uni_unilag',
    level: '200',
    semester: '1st',
    description: 'Kirchhoff’s laws, mesh and nodal analysis, Thevenin and Norton theorems, AC sinusoidal steady state, phasors.',
    status: 'active',
    mastery_percentage: 55,
    question_count: 45,
  },
  {
    id: 'course_eco201',
    code: 'ECO 201',
    title: 'Principles of Microeconomics',
    department_id: 'dept_eco',
    faculty_id: 'fac_soc',
    university_id: 'uni_unilag',
    level: '200',
    semester: '1st',
    description: 'Consumer choice, price elasticity, market structures (perfect competition, monopoly, oligopoly), production costs.',
    status: 'active',
    mastery_percentage: 82,
    question_count: 75,
  },
];

export const TOPICS: Topic[] = [
  // CSC 201 Topics
  { id: 'top_csc201_1', course_id: 'course_csc201', name: 'Arrays & Linked Lists', mastery_percentage: 85, question_count: 22 },
  { id: 'top_csc201_2', course_id: 'course_csc201', name: 'Stacks & Queues', mastery_percentage: 80, question_count: 18 },
  { id: 'top_csc201_3', course_id: 'course_csc201', name: 'Trees & Binary Search Trees', mastery_percentage: 65, question_count: 20 },
  { id: 'top_csc201_4', course_id: 'course_csc201', name: 'Sorting & Searching Algorithms', mastery_percentage: 72, question_count: 15 },
  { id: 'top_csc201_5', course_id: 'course_csc201', name: 'Asymptotic Analysis & Big-O', mastery_percentage: 58, question_count: 10 },
  
  // CSC 203 Topics
  { id: 'top_csc203_1', course_id: 'course_csc203', name: 'Logic Gates & Boolean Algebra', mastery_percentage: 75, question_count: 15 },
  { id: 'top_csc203_2', course_id: 'course_csc203', name: 'CPU Architecture & ALU', mastery_percentage: 60, question_count: 15 },
  { id: 'top_csc203_3', course_id: 'course_csc203', name: 'Memory Hierarchy & Cache Mapping', mastery_percentage: 50, question_count: 18 },
  { id: 'top_csc203_4', course_id: 'course_csc203', name: 'Instruction Sets & Pipelining', mastery_percentage: 55, question_count: 12 },

  // MTH 201 Topics
  { id: 'top_mth201_1', course_id: 'course_mth201', name: 'Matrices & Determinants', mastery_percentage: 80, question_count: 25 },
  { id: 'top_mth201_2', course_id: 'course_mth201', name: 'Vector Spaces & Subspaces', mastery_percentage: 68, question_count: 20 },
  { id: 'top_mth201_3', course_id: 'course_mth201', name: 'Eigenvalues & Eigenvectors', mastery_percentage: 54, question_count: 25 },
  { id: 'top_mth201_4', course_id: 'course_mth201', name: 'Linear Transformations', mastery_percentage: 62, question_count: 20 },

  // WAEC Mathematics Topics
  { id: 'top_waec_mth_1', subject_id: 'subj_mth', name: 'Quadratic Equations & Polynomials', mastery_percentage: 88, question_count: 45 },
  { id: 'top_waec_mth_2', subject_id: 'subj_mth', name: 'Trigonometry & Bearings', mastery_percentage: 68, question_count: 40 },
  { id: 'top_waec_mth_3', subject_id: 'subj_mth', name: 'Statistics & Probability', mastery_percentage: 82, question_count: 38 },
  { id: 'top_waec_mth_4', subject_id: 'subj_mth', name: 'Logarithms & Indices', mastery_percentage: 90, question_count: 35 },
  { id: 'top_waec_mth_5', subject_id: 'subj_mth', name: 'Mensuration & Solid Geometry', mastery_percentage: 60, question_count: 32 },
  { id: 'top_waec_mth_6', subject_id: 'subj_mth', name: 'Calculus (Differentiation & Integration)', mastery_percentage: 55, question_count: 25 },

  // WAEC English Topics
  { id: 'top_waec_eng_1', subject_id: 'subj_eng', name: 'Lexis & Structure', mastery_percentage: 84, question_count: 50 },
  { id: 'top_waec_eng_2', subject_id: 'subj_eng', name: 'Synonyms & Antonyms', mastery_percentage: 86, question_count: 45 },
  { id: 'top_waec_eng_3', subject_id: 'subj_eng', name: 'Oral English & Phonetics', mastery_percentage: 70, question_count: 40 },
  { id: 'top_waec_eng_4', subject_id: 'subj_eng', name: 'Reading Comprehension', mastery_percentage: 92, question_count: 30 },

  // WAEC Physics Topics
  { id: 'top_waec_phy_1', subject_id: 'subj_phy', name: 'Mechanics & Newton’s Laws', mastery_percentage: 74, question_count: 40 },
  { id: 'top_waec_phy_2', subject_id: 'subj_phy', name: 'Waves & Sound / Optics', mastery_percentage: 66, question_count: 35 },
  { id: 'top_waec_phy_3', subject_id: 'subj_phy', name: 'Current Electricity & Magnetism', mastery_percentage: 62, question_count: 38 },
  { id: 'top_waec_phy_4', subject_id: 'subj_phy', name: 'Thermal Physics & Heat Energy', mastery_percentage: 78, question_count: 30 },
  { id: 'top_waec_phy_5', subject_id: 'subj_phy', name: 'Atomic & Nuclear Physics', mastery_percentage: 58, question_count: 24 },

  // WAEC Chemistry Topics
  { id: 'top_waec_chm_1', subject_id: 'subj_chm', name: 'Periodic Table & Chemical Bonding', mastery_percentage: 80, question_count: 38 },
  { id: 'top_waec_chm_2', subject_id: 'subj_chm', name: 'Stoichiometry & Mole Concept', mastery_percentage: 62, question_count: 36 },
  { id: 'top_waec_chm_3', subject_id: 'subj_chm', name: 'Acids, Bases & Salts / Redox', mastery_percentage: 75, question_count: 34 },
  { id: 'top_waec_chm_4', subject_id: 'subj_chm', name: 'Organic Chemistry & Hydrocarbons', mastery_percentage: 58, question_count: 42 },

  // WAEC Biology Topics
  { id: 'top_waec_bio_1', subject_id: 'subj_bio', name: 'Cell Biology & Heredity (Genetics)', mastery_percentage: 76, question_count: 40 },
  { id: 'top_waec_bio_2', subject_id: 'subj_bio', name: 'Ecology, Habitat & Food Chains', mastery_percentage: 88, question_count: 35 },
  { id: 'top_waec_bio_3', subject_id: 'subj_bio', name: 'Human Physiology & Circulatory System', mastery_percentage: 82, question_count: 42 },
];

export const WAEC_SUBJECTS: WAECSubject[] = [
  { id: 'subj_mth', name: 'Mathematics', code: 'MTH', category: 'General', description: 'General Mathematics covering Algebra, Geometry, Trigonometry, Statistics & Calculus.', question_count: 215, topics_count: 6, mastery_percentage: 76, status: 'active' },
  { id: 'subj_eng', name: 'English Language', code: 'ENG', category: 'General', description: 'Grammar, lexis, antonyms, idioms, phonetics and comprehension reading.', question_count: 190, topics_count: 4, mastery_percentage: 83, status: 'active' },
  { id: 'subj_phy', name: 'Physics', code: 'PHY', category: 'Science', description: 'Classical Mechanics, Thermodynamics, Waves, Optics, Electricity and Modern Physics.', question_count: 175, topics_count: 5, mastery_percentage: 68, status: 'active' },
  { id: 'subj_chm', name: 'Chemistry', code: 'CHM', category: 'Science', description: 'Inorganic, Physical and Organic Chemistry, stoichiometry, and industrial processes.', question_count: 160, topics_count: 4, mastery_percentage: 71, status: 'active' },
  { id: 'subj_bio', name: 'Biology', code: 'BIO', category: 'Science', description: 'Living organisms, cellular structure, physiology, genetics, evolution and ecology.', question_count: 185, topics_count: 3, mastery_percentage: 80, status: 'active' },
  { id: 'subj_eco', name: 'Economics', code: 'ECO', category: 'Commercial', description: 'Micro and macro economics, financial institutions, national budgets and development.', question_count: 140, topics_count: 4, mastery_percentage: 75, status: 'active' },
  { id: 'subj_gov', name: 'Government', code: 'GOV', category: 'Arts', description: 'Political systems, Nigerian constitutional development, colonial rule and diplomacy.', question_count: 130, topics_count: 4, mastery_percentage: 79, status: 'active' },
  { id: 'subj_lit', name: 'Literature in English', code: 'LIT', category: 'Arts', description: 'African and Non-African prose, drama, poetry analysis and literary devices.', question_count: 110, topics_count: 3, mastery_percentage: 72, status: 'active' },
  { id: 'subj_acc', name: 'Financial Accounting', code: 'ACC', category: 'Commercial', description: 'Bookkeeping, balance sheets, ledger accounts, cash flow statements and ratios.', question_count: 95, topics_count: 3, mastery_percentage: 65, status: 'active' },
];

export const INITIAL_QUESTIONS: Question[] = [
  // --- REAL PAST QUESTIONS (UNILAG CSC 201) ---
  {
    id: 'q_csc201_real_01',
    question_text: 'In a singly linked list with n nodes, what is the worst-case time complexity to delete a node given only a pointer to the node itself (not the head), without knowing the predecessor?',
    question_type: 'multiple_choice',
    source_type: 'real_past_question',
    verification_status: 'verified',
    exam_type: 'university',
    institution_id: 'uni_unilag',
    institution_name: 'University of Lagos',
    faculty_name: 'Faculty of Science',
    department_name: 'Computer Science',
    course_id: 'course_csc201',
    course_code: 'CSC 201',
    course_title: 'Data Structures and Algorithms',
    topic_name: 'Arrays & Linked Lists',
    year: 2024,
    semester: '1st',
    level: '200',
    options: [
      { id: 'A', text: 'O(1) by copying data from the next node and bypassing it (for non-tail nodes)' },
      { id: 'B', text: 'O(n) because traversing from head is always required' },
      { id: 'C', text: 'O(log n) using binary pointer references' },
      { id: 'D', text: 'O(n²) due to memory reallocation' },
    ],
    correct_answer: 'A',
    explanation: 'If we are given only a pointer to the node to be deleted (node X, provided it is not the last node), we can copy the value of node X->next into node X, and then delete node X->next by setting X->next = X->next->next in O(1) time.',
    difficulty: 'medium',
    source: 'Official UNILAG 2023/2024 CSC 201 1st Semester Examination (Paper A, Q4)',
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'q_csc201_real_02',
    question_text: 'Which of the following sorting algorithms is NOT stable in its standard in-place implementation?',
    question_type: 'multiple_choice',
    source_type: 'real_past_question',
    verification_status: 'verified',
    exam_type: 'university',
    institution_id: 'uni_unilag',
    institution_name: 'University of Lagos',
    faculty_name: 'Faculty of Science',
    department_name: 'Computer Science',
    course_id: 'course_csc201',
    course_code: 'CSC 201',
    course_title: 'Data Structures and Algorithms',
    topic_name: 'Sorting & Searching Algorithms',
    year: 2023,
    semester: '1st',
    level: '200',
    options: [
      { id: 'A', text: 'Merge Sort' },
      { id: 'B', text: 'Insertion Sort' },
      { id: 'C', text: 'Quick Sort' },
      { id: 'D', text: 'Bubble Sort' },
    ],
    correct_answer: 'C',
    explanation: 'Standard in-place Quick Sort swaps elements across long distances around the pivot, which can change the relative order of equal keys. In contrast, standard Merge Sort, Insertion Sort, and Bubble Sort maintain the relative order of duplicate elements.',
    difficulty: 'easy',
    source: 'Official UNILAG 2022/2023 CSC 201 Examination (Q11)',
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'q_csc201_real_03',
    question_text: 'What is the maximum number of nodes at level k (root is at level 0) of a binary tree?',
    question_type: 'multiple_choice',
    source_type: 'real_past_question',
    verification_status: 'verified',
    exam_type: 'university',
    institution_id: 'uni_unilag',
    institution_name: 'University of Lagos',
    faculty_name: 'Faculty of Science',
    department_name: 'Computer Science',
    course_id: 'course_csc201',
    course_code: 'CSC 201',
    course_title: 'Data Structures and Algorithms',
    topic_name: 'Trees & Binary Search Trees',
    year: 2024,
    semester: '1st',
    level: '200',
    options: [
      { id: 'A', text: '2^k' },
      { id: 'B', text: '2^(k+1) - 1' },
      { id: 'C', text: '2k' },
      { id: 'D', text: 'k²' },
    ],
    correct_answer: 'A',
    explanation: 'Level 0 has at most 2^0 = 1 node. Level 1 has at most 2^1 = 2 nodes. In general, level k has at most 2^k nodes. Note that 2^(k+1) - 1 is the total cumulative maximum nodes in a tree of height k.',
    difficulty: 'easy',
    source: 'Official UNILAG 2023/2024 CSC 201 Examination (Q18)',
    created_at: '2026-01-15T10:00:00Z',
  },

  // --- REAL PAST QUESTIONS (WAEC MATHEMATICS) ---
  {
    id: 'q_waec_mth_real_01',
    question_text: 'If log₁₀ 2 = 0.3010 and log₁₀ 3 = 0.4771, calculate the value of log₁₀ 72 without using mathematical tables.',
    question_type: 'multiple_choice',
    source_type: 'real_past_question',
    verification_status: 'verified',
    exam_type: 'waec',
    subject_id: 'subj_mth',
    subject_name: 'Mathematics',
    topic_name: 'Logarithms & Indices',
    year: 2023,
    options: [
      { id: 'A', text: '1.8572' },
      { id: 'B', text: '1.7781' },
      { id: 'C', text: '1.9542' },
      { id: 'D', text: '2.1430' },
    ],
    correct_answer: 'A',
    explanation: 'Express 72 as prime factors: 72 = 2³ × 3².\nlog₁₀ 72 = log₁₀(2³ × 3²) = 3(log₁₀ 2) + 2(log₁₀ 3)\n= 3(0.3010) + 2(0.4771) = 0.9030 + 0.9542 = 1.8572.',
    difficulty: 'medium',
    source: 'WAEC May/June 2023 WASSCE General Mathematics Paper 2 (Theory Part I, Q2a)',
    created_at: '2026-01-10T12:00:00Z',
  },
  {
    id: 'q_waec_mth_real_02',
    question_text: 'Solve for x in the quadratic equation 3x² - 5x - 2 = 0.',
    question_type: 'multiple_choice',
    source_type: 'real_past_question',
    verification_status: 'verified',
    exam_type: 'waec',
    subject_id: 'subj_mth',
    subject_name: 'Mathematics',
    topic_name: 'Quadratic Equations & Polynomials',
    year: 2024,
    options: [
      { id: 'A', text: 'x = 2 or x = -1/3' },
      { id: 'B', text: 'x = -2 or x = 1/3' },
      { id: 'C', text: 'x = 3 or x = -2/3' },
      { id: 'D', text: 'x = 1/2 or x = -2' },
    ],
    correct_answer: 'A',
    explanation: '3x² - 5x - 2 = 0\nFactorizing: product = -6, sum = -5 -> factors are -6 and 1\n3x² - 6x + x - 2 = 0\n3x(x - 2) + 1(x - 2) = 0\n(3x + 1)(x - 2) = 0\nTherefore, x = 2 or x = -1/3.',
    difficulty: 'easy',
    source: 'WAEC May/June 2024 WASSCE General Mathematics Paper 1 (Objective Q14)',
    created_at: '2026-01-10T12:00:00Z',
  },
  {
    id: 'q_waec_mth_real_03',
    question_text: 'A ladder 13m long leans against a vertical wall. If the foot of the ladder is 5m away from the base of the wall, find the angle of elevation of the ladder to the horizontal (to the nearest degree).',
    question_type: 'multiple_choice',
    source_type: 'real_past_question',
    verification_status: 'verified',
    exam_type: 'waec',
    subject_id: 'subj_mth',
    subject_name: 'Mathematics',
    topic_name: 'Trigonometry & Bearings',
    year: 2022,
    options: [
      { id: 'A', text: '67°' },
      { id: 'B', text: '23°' },
      { id: 'C', text: '60°' },
      { id: 'D', text: '72°' },
    ],
    correct_answer: 'A',
    explanation: 'Let θ be the angle with the ground.\ncos θ = Adjacent / Hypotenuse = 5 / 13 = 0.3846.\nθ = arccos(0.3846) ≈ 67.38° -> 67° to the nearest degree.',
    difficulty: 'medium',
    source: 'WAEC May/June 2022 WASSCE General Mathematics Paper 1 (Objective Q33)',
    created_at: '2026-01-10T12:00:00Z',
  },

  // --- REAL PAST QUESTIONS (WAEC PHYSICS) ---
  {
    id: 'q_waec_phy_real_01',
    question_text: 'An object of mass 5kg is released from rest from a height of 20m above the ground. Calculate its kinetic energy just before striking the ground (Take g = 10 m/s²).',
    question_type: 'multiple_choice',
    source_type: 'real_past_question',
    verification_status: 'verified',
    exam_type: 'waec',
    subject_id: 'subj_phy',
    subject_name: 'Physics',
    topic_name: 'Mechanics & Newton’s Laws',
    year: 2023,
    options: [
      { id: 'A', text: '1000 J' },
      { id: 'B', text: '500 J' },
      { id: 'C', text: '2000 J' },
      { id: 'D', text: '100 J' },
    ],
    correct_answer: 'A',
    explanation: 'By the law of conservation of mechanical energy:\nKinetic Energy at impact = Potential Energy at release = m × g × h\n= 5 kg × 10 m/s² × 20 m = 1000 Joules.',
    difficulty: 'easy',
    source: 'WAEC May/June 2023 WASSCE Physics Paper 1 (Objective Q8)',
    created_at: '2026-01-12T09:00:00Z',
  },

  // --- AI GENERATED QUESTIONS (Clearly marked as AI Generated) ---
  {
    id: 'q_ai_gen_csc201_01',
    question_text: 'Consider an AVL tree. After inserting a new element that causes an imbalance where the balance factor of node A is +2 and its left child B has a balance factor of -1, what specific rotation is required to restore AVL property?',
    question_type: 'multiple_choice',
    source_type: 'ai_generated',
    verification_status: 'verified',
    exam_type: 'university',
    course_id: 'course_csc201',
    course_code: 'CSC 201',
    course_title: 'Data Structures and Algorithms',
    topic_name: 'Trees & Binary Search Trees',
    options: [
      { id: 'A', text: 'Left-Right (LR) Double Rotation' },
      { id: 'B', text: 'Single Right Rotation' },
      { id: 'C', text: 'Right-Left (RL) Double Rotation' },
      { id: 'D', text: 'Single Left Rotation' },
    ],
    correct_answer: 'A',
    explanation: 'When node A has a balance factor of +2 (left-heavy) and its left child has a balance factor of -1 (right-heavy), it constitutes a Left-Right (LR) case. This is solved by first performing a Left rotation on child B, followed by a Right rotation on node A.',
    difficulty: 'hard',
    source: 'AI Generated Practice — Topic Pattern Analysis (AVL Trees & Rotations)',
    ai_pattern_basis: 'Generated based on recurring UNILAG 200-level balanced search tree exam questions',
    created_at: '2026-02-01T14:00:00Z',
  },
  {
    id: 'q_ai_gen_waec_mth_01',
    question_text: 'If the roots of the equation 2x² - px + 8 = 0 are equal, find the possible values of the constant p.',
    question_type: 'multiple_choice',
    source_type: 'ai_generated',
    verification_status: 'verified',
    exam_type: 'waec',
    subject_id: 'subj_mth',
    subject_name: 'Mathematics',
    topic_name: 'Quadratic Equations & Polynomials',
    options: [
      { id: 'A', text: 'p = ±8' },
      { id: 'B', text: 'p = ±4' },
      { id: 'C', text: 'p = ±16' },
      { id: 'D', text: 'p = 8 only' },
    ],
    correct_answer: 'A',
    explanation: 'For a quadratic equation ax² + bx + c = 0 to have equal (repeated) roots, the discriminant must be zero: b² - 4ac = 0.\nHere a = 2, b = -p, c = 8.\n(-p)² - 4(2)(8) = 0\np² - 64 = 0\np² = 64 -> p = ±8.',
    difficulty: 'medium',
    source: 'AI Generated Practice — WAEC Syllabus Quadratic Discriminant Pattern',
    ai_pattern_basis: 'Modeled after WAEC repeated root / discriminant exam trends',
    created_at: '2026-02-01T14:00:00Z',
  }
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: 'ach_first_test', title: 'First Steps', description: 'Complete your first practice exam or test simulation', icon_name: 'Trophy', category: 'tests', xp_reward: 100, is_unlocked: true, unlocked_at: '2026-08-20T10:00:00Z', progress: 1, max_progress: 1 },
  { id: 'ach_100_q', title: 'Century Scholar', description: 'Answer 100 questions across any subject or course', icon_name: 'Target', category: 'mastery', xp_reward: 250, is_unlocked: true, unlocked_at: '2026-08-24T18:30:00Z', progress: 100, max_progress: 100 },
  { id: 'ach_500_q', title: 'Master of Questions', description: 'Answer 500 questions across WAEC and university courses', icon_name: 'Flame', category: 'mastery', xp_reward: 600, is_unlocked: false, progress: 142, max_progress: 500 },
  { id: 'ach_streak_7', title: '7-Day Streak', description: 'Study consistently for 7 consecutive days', icon_name: 'Zap', category: 'streak', xp_reward: 350, is_unlocked: true, unlocked_at: '2026-08-26T08:00:00Z', progress: 7, max_progress: 7 },
  { id: 'ach_streak_30', title: 'Unstoppable Momentum', description: 'Maintain a 30-day active study streak', icon_name: 'Calendar', category: 'streak', xp_reward: 1200, is_unlocked: false, progress: 7, max_progress: 30 },
  { id: 'ach_score_90', title: 'Top Percentile', description: 'Score 90% or higher in any full-length exam simulation', icon_name: 'Award', category: 'mastery', xp_reward: 400, is_unlocked: true, unlocked_at: '2026-08-25T14:20:00Z', progress: 1, max_progress: 1 },
  { id: 'ach_perfect', title: 'Flawless 100%', description: 'Achieve a perfect 100% score on a 20+ question test', icon_name: 'Crown', category: 'special', xp_reward: 800, is_unlocked: false, progress: 0, max_progress: 1 },
  { id: 'ach_uploader', title: 'Community Contributor', description: 'Upload a legitimate past question document for moderation', icon_name: 'UploadCloud', category: 'uploads', xp_reward: 300, is_unlocked: true, unlocked_at: '2026-08-22T11:15:00Z', progress: 1, max_progress: 1 },
];

export const INITIAL_UPLOADS: UploadRecord[] = [
  {
    id: 'up_001',
    user_id: 'user_student_1',
    user_name: 'Chioma Adeleke',
    user_email: 'chioma.adeleke@student.unilag.edu.ng',
    file_name: 'CSC201_2023_Harmattan_Exam.pdf',
    file_type: 'application/pdf',
    file_size: '2.4 MB',
    exam_type: 'university',
    university_name: 'University of Lagos',
    faculty_name: 'Faculty of Science',
    department_name: 'Computer Science',
    level: '200',
    course_code: 'CSC 201',
    course_title: 'Data Structures and Algorithms',
    semester: '1st',
    year: 2023,
    notes: 'Scanned official Department paper from January 2023 session with 40 objective questions.',
    extracted_text: 'UNIVERSITY OF LAGOS\nFACULTY OF SCIENCE\nDEPARTMENT OF COMPUTER SCIENCE\nFIRST SEMESTER EXAMINATION 2022/2023\nCOURSE: CSC 201 - DATA STRUCTURES (3 UNITS)\nTIME ALLOWED: 2 HOURS\nINSTRUCTIONS: Answer all questions in Section A.\n\n1. What is the time complexity to search an unordered linked list?\nA) O(1) B) O(log n) C) O(n) D) O(n^2)\nAnswer: C\n\n2. Which traversal of a Binary Search Tree produces sorted values?\nA) Pre-order B) In-order C) Post-order D) Level-order\nAnswer: B',
    status: 'approved',
    created_at: '2026-08-20T14:10:00Z',
    reviewed_at: '2026-08-21T09:30:00Z',
    moderator_notes: 'Verified against department records and imported into public library.',
  },
  {
    id: 'up_002',
    user_id: 'user_student_2',
    user_name: 'Ibrahim Danjuma',
    user_email: 'ibrahim.d@abu.edu.ng',
    file_name: 'WAEC_Physics_2024_Paper1.pdf',
    file_type: 'application/pdf',
    file_size: '3.1 MB',
    exam_type: 'waec',
    subject_name: 'Physics',
    year: 2024,
    notes: 'Official WAEC 2024 Physics Paper 1 with complete 50 objective questions.',
    extracted_text: 'WEST AFRICAN SENIOR SCHOOL CERTIFICATE EXAMINATION\nMAY/JUNE 2024\nPHYSICS 1 (OBJECTIVE TEST)\n1. Which of the following is a fundamental physical quantity?\nA) Electric current B) Velocity C) Force D) Density\nAnswer: A',
    status: 'pending_review',
    created_at: '2026-08-25T16:45:00Z',
  },
  {
    id: 'up_003',
    user_id: 'user_student_3',
    user_name: 'Tunde Bakare',
    user_email: 'tunde.bakare@gmail.com',
    file_name: 'MTH201_OAU_2022_Midterm.jpg',
    file_type: 'image/jpeg',
    file_size: '1.8 MB',
    exam_type: 'university',
    university_name: 'Obafemi Awolowo University',
    faculty_name: 'Faculty of Science',
    department_name: 'Mathematics',
    level: '200',
    course_code: 'MTH 201',
    course_title: 'Linear Algebra',
    semester: '1st',
    year: 2022,
    notes: 'Midterm test question sheet on Eigenvalues and Linear Transformations.',
    extracted_text: 'OBAFEMI AWOLOWO UNIVERSITY, ILE-IFE\nDEPARTMENT OF MATHEMATICS\nMTH 201 - LINEAR ALGEBRA I (CONTINUOUS ASSESSMENT TEST)\nFind the eigenvalues of matrix A = [[2, 1], [1, 2]].',
    status: 'pending_review',
    created_at: '2026-08-26T11:20:00Z',
  }
];

export const CUSTOM_INSTITUTION_AGGREGATES: CustomInstitutionAggregate[] = [
  {
    name: 'Nile University of Nigeria',
    type: 'university',
    student_count: 312,
    first_submitted_at: '2026-06-10T08:00:00Z',
    last_submitted_at: '2026-08-25T14:15:00Z',
  },
  {
    name: 'Babcock University',
    type: 'university',
    student_count: 247,
    first_submitted_at: '2026-05-18T11:20:00Z',
    last_submitted_at: '2026-08-26T09:40:00Z',
  },
  {
    name: 'Faculty of Renewable Natural Resources',
    type: 'faculty',
    parent_name: 'University of Ibadan',
    student_count: 89,
    first_submitted_at: '2026-07-01T15:00:00Z',
    last_submitted_at: '2026-08-24T19:10:00Z',
  },
  {
    name: 'Mechatronics Engineering',
    type: 'department',
    parent_name: 'Federal University of Technology, Akure',
    student_count: 145,
    first_submitted_at: '2026-06-22T10:30:00Z',
    last_submitted_at: '2026-08-26T10:00:00Z',
  }
];

export const INITIAL_EXAM_RESULTS: ExamResult[] = [
  {
    id: 'res_001',
    exam_session_id: 'sess_prev_1',
    user_id: 'user_student_1',
    title: 'CSC 201 Full-Length Exam Simulation',
    exam_type: 'university',
    category_name: 'CSC 201: Data Structures and Algorithms',
    source_type: 'real_past_question',
    total_questions: 20,
    correct_count: 17,
    incorrect_count: 3,
    skipped_count: 0,
    score_percentage: 85,
    time_used_seconds: 1140,
    completed_at: '2026-08-25T15:30:00Z',
    xp_earned: 170,
    topic_breakdown: [
      { topic: 'Arrays & Linked Lists', total: 6, correct: 6, percentage: 100 },
      { topic: 'Stacks & Queues', total: 5, correct: 5, percentage: 100 },
      { topic: 'Trees & Binary Search Trees', total: 5, correct: 3, percentage: 60 },
      { topic: 'Asymptotic Analysis & Big-O', total: 4, correct: 3, percentage: 75 },
    ],
    questions: INITIAL_QUESTIONS.slice(0, 3),
    user_answers: {
      q_csc201_real_01: 'A',
      q_csc201_real_02: 'C',
      q_csc201_real_03: 'A',
    },
  },
  {
    id: 'res_002',
    exam_session_id: 'sess_prev_2',
    user_id: 'user_student_1',
    title: 'WAEC Mathematics 2023 Past Exam Drill',
    exam_type: 'waec',
    category_name: 'WAEC Mathematics',
    source_type: 'real_past_question',
    total_questions: 15,
    correct_count: 13,
    incorrect_count: 2,
    skipped_count: 0,
    score_percentage: 87,
    time_used_seconds: 820,
    completed_at: '2026-08-24T18:20:00Z',
    xp_earned: 130,
    topic_breakdown: [
      { topic: 'Quadratic Equations & Polynomials', total: 5, correct: 5, percentage: 100 },
      { topic: 'Logarithms & Indices', total: 5, correct: 5, percentage: 100 },
      { topic: 'Trigonometry & Bearings', total: 5, correct: 3, percentage: 60 },
    ],
    questions: INITIAL_QUESTIONS.slice(3, 6),
    user_answers: {
      q_waec_mth_real_01: 'A',
      q_waec_mth_real_02: 'A',
      q_waec_mth_real_03: 'A',
    },
  },
  {
    id: 'res_003',
    exam_session_id: 'sess_prev_3',
    user_id: 'user_student_1',
    title: 'AI Targeted Practice: Trees & Big-O',
    exam_type: 'university',
    category_name: 'CSC 201: Data Structures and Algorithms',
    source_type: 'ai_generated',
    total_questions: 10,
    correct_count: 7,
    incorrect_count: 3,
    skipped_count: 0,
    score_percentage: 70,
    time_used_seconds: 560,
    completed_at: '2026-08-26T09:15:00Z',
    xp_earned: 70,
    topic_breakdown: [
      { topic: 'Trees & Binary Search Trees', total: 6, correct: 4, percentage: 67 },
      { topic: 'Asymptotic Analysis & Big-O', total: 4, correct: 3, percentage: 75 },
    ],
    questions: INITIAL_QUESTIONS.slice(0, 2),
    user_answers: {
      q_csc201_real_01: 'A',
      q_csc201_real_02: 'C',
    },
  }
];

export const CURRENT_USER: User = {
  id: 'user_student_1',
  name: 'Chioma Adeleke',
  email: 'chioma.adeleke@student.unilag.edu.ng',
  role: 'student',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  created_at: '2026-08-01T08:00:00Z',
  profile: {
    education_type: 'both', // Enrolled in both university & WAEC prep
    university_id: 'uni_unilag',
    custom_university_name: null,
    faculty_id: 'fac_sci',
    custom_faculty_name: null,
    department_id: 'dept_csc',
    custom_department_name: null,
    level: '200',
    semester: '1st',
    selected_courses: ['CSC 201', 'CSC 203', 'MTH 201', 'GST 101'],
    selected_waec_subjects: ['Mathematics', 'English Language', 'Physics', 'Chemistry'],
    waec_target_year: 2026,
    xp: 2840,
    streak_days: 7,
    last_active_date: '2026-08-26',
    overall_mastery_percentage: 78,
    total_questions_answered: 142,
    total_tests_completed: 18,
    average_score_percentage: 81,
    best_score_percentage: 95,
  }
};
